services:
  db:
    container_name: bill-test-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    container_name: bill-test-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data: