services:
#  back:
#    container_name: bill-ktor
#    image: registry.cn-hangzhou.aliyuncs.com/fadinglight/bill-ktor:dev
#    restart: always
#    environment:
#      JDBC_URL: mariadb://db/bill
#    ports:
#      - 80:4000

  db:
    container_name: bill-test-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    container_name: bill-test-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data: